blog post mlr vs. caret
mlr-org/mlr-web pull request #8
Opened 2018-11-20 20:51 UTC by PhilippPro

I could add more code samples in the sections.

2018-11-21 09:54 UTC, jakob-r commented
I guess I can not see the post in the preview because the date is set to 25.11?
I guess the html file should not be included in the PR?

2018-11-21 11:52 UTC, PhilippPro commented
> 5. Commit the Rmd and HTML file and possible external resources.

2018-11-21 12:33 UTC, PhilippPro commented
Ok, it was the date, you can see the post now in its full "beauty". ;) I think I should add more code, otherwise people get tired while reading it. ;)

2018-11-21 14:00 UTC, pat-s commented
Great! So the system works. I'll review later and would also forward the post to [rweekly](https://github.com/rweekly/rweekly.org).

2018-11-23 12:46 UTC, PhilippPro commented
Maybe it would be nice to have simple wrappers in mlr so you can just do everything in a one-liner, for example: 
```
library(mlr)
benchmark_lazy(c("svm", "xgboost"), iris, "classif", "randomsearch")
```
Or even shorter:
`benchmark_lazy(data = iris)`
or 
`train_lazy(data = iris)`

Just an idea. ;)

2018-12-06 10:25 UTC, pat-s requested changes
Thanks for this post @PhilippPro.
I did a thorough review and improved some wordings.

Two general questions:

- Why is the code always `eval = FALSE`?
- Please use a new line for each sentence. This makes reviewing easier as specific sentences can be targeted. I will add this point to the README.

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +**caret** is longer on the market, its first CRAN release seems to be from 2007, while **mlr** came to CRAN on 2013. As for now, **caret** seems to be more popular, according to [**cranlogs**](https:
```suggestion
**caret** is longer on the market, its first CRAN release is from 2007, while **mlr** came to CRAN on 2013. 
As for now, **caret** seems to be more popular, according to [**cranlogs**](https://cran.r-project.org/web/packages/cranlogs/index.html). 
**caret** was downloaded 178029 times while **mlr** sums up to 11408 downloads in the last 30 days.
```

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +The purpose of the packages seems to be quite similar. The **caret** [website](https://github.com/topepo/caret) defines **caret** as follows:
```suggestion
The purpose of the packages seems to be quite similar. 
The **caret** [website](https://github.com/topepo/caret) defines **caret** as follows:
```

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +> *The caret package (short for Classification And REgression Training) is a set of functions that attempt to streamline the process for creating predictive models.*
```suggestion
> *The caret package (short for Classification And Regression Training) is a set of functions that attempt to streamline the process for creating predictive models.*
```

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +Both packages want to automatize standard processes for standard tasks like classification and regression and make life easier for data scientists.
```suggestion
Both packages aim to automatize processes for standard tasks like classification and regression and make life easier for data scientists.
```

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +I will try to do a fair comparison of these two packages. As I contributed to the **mlr** package I may be biased, but I will try to do it as fair as possible.
```suggestion
This post aims on doing a fair comparison between these two packages. 
As the author of this post contributed to the development of **mlr** the view may be biased.
```

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +Both packages heavily depend on other packages and hence installation takes a long time. I tested both packages on my windows machine with a fresh R version and without having installed any dependenc
```suggestion
Both packages heavily depend on other packages and hence installation takes a long time. 
I tested both packages on my Windows machine with a fresh R version (3.5.1 at the time writing) and without having installed any dependencies beforehand. 
For **caret** it took 140 seconds to install while **mlr** needed 46 seconds (without including suggested packages).
```

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +Both have an online tutorial. [**caret**`s one](http://topepo.github.io/caret/index.html) is good for learning from scratch, but for looking things up quickly it is rather unpractical. Here lies the
```suggestion
Both have an online tutorial. 
[**caret**`s one](http://topepo.github.io/caret/index.html) is good for learning from scratch, but for looking things up quickly it is rather unpractical. 
Here lies the strength of the [**mlr** tutorial](https://mlr.mlr-org.com/index.html).
```

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +**caret** provides more things. There is the [Applied Predictive Modelling book](https://www.springer.com/de/book/9781461468486) which tries to *cover the overall predictive modeling process.* It is
> **caret** provides more things.

Sounds too general here. Maybe you can be more specific.

Listing all the R books does not seem so beneficial here.

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +Moreover there is a [datacamp course](https://www.datacamp.com/courses/machine-learning-toolbox) that uses **caret**.
Should we try to avoid linking to commercial offers?

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +To compare the two packages directly here you can see the standard codes of lines that are necessary to perform a simple 5-fold cross-validation for the boston housing dataset and with the random for
```suggestion
To compare the two packages directly here you can see the standard codes of lines that are necessary to perform a simple 5-fold cross-validation for the boston housing dataset using the random forest package [**ranger**](https://github.com/imbs-hl/ranger).
```

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +For **mlr**:
```suggestion
**mlr**:
```

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +For **caret**:
```suggestion
**caret**:
```

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +```{r, eval = FALSE}
Why `eval = FALSE`?

If so, then the output of `res` and `fit` should appear here.

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +In this code you can already see a crucial difference. In **mlr** you have to create a task and a learner. This means more code writing, but gives the user also more flexibility and overview of what
```suggestion
In this code you can already see a crucial difference. 
In **mlr** you have to create a task and a learner. 
This means more code writing, but gives the user also more flexibility and overview of what is being done. 
In **caret** you can pass the data and the method directly to the `train()` function and internally some tuning is done for the user without having the possibility to adjust this easily.
```

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +In this code you can already see a crucial difference. In **mlr** you have to create a task and a learner. This means more code writing, but gives the user also more flexibility and overview of what
> internally some tuning is done for the user without having the possibility to adjust this easily.

I would say this needs a bit more explanation?

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +Things can be changed in both packages (e.g., by giving directly the character ```"regr.ranger"``` as learner in ```train``` or by creating your own learner in **caret** like described [here](http://
```suggestion
This behavior can be changed in both packages, e.g., by directly passing the character `"regr.ranger"` as the learner argument to `train()` or by creating a custom learner in **caret** as described [here](http://topepo.github.io/caret/using-your-own-model-in-train.html).
```

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +Let`s compare the different feature that the two packages have to offer for different issues of the machine learning process.
```suggestion
Let`s compare the different features that the two packages have to offer for different issues of the machine learning process.
```

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +Both packages have several possibilities for preprocessing of the dataset. Both include standard procedures like dummy feature creation (e.g. for categorical predictors), normalization and imputation
```suggestion
Both packages have several possibilities for preprocessing the data. 
Standard procedures like dummy feature creation (e.g. for categorical predictors), normalization and imputation and feature selection methods are included. 
In **caret** also standard transformations (scaling, PCA, Box-Cox, Yeo-Johnson, etc.) can be used. 
An advantage of **mlr** is, that all preprocessing methods of **caret** can be used via the wrapper function `makePreprocWrapperCaret()`. 
Both provide the option to use these preprocessing steps also in the resampling process.
```

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +**mlr** has more possibilities to create different tasks: Classification, Regression, Survival, Clustering, Multilabel, Cost-sensitive, Imbalanced data, Functional data, Spatial data.
```suggestion
**mlr** supports a larger variety of tasks, such as classification, regression, survival, clustering, multilabel, cost-sensitive, imbalanced data, functional data and spatial data.
```

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +**caret** only seems to have possibilities for Classification, Regression and Cost-sensitive.
```suggestion
**caret** only seems to be usable for classification, regression and cost-sensitive.
```

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +Currently 271 learners are supported in **caret**. For **mlr** there are *only* 165. I think bigger quantity is not very important here, as the most common and most important learners are implemented
```suggestion
Currently 271 learners are supported in **caret**. 
For **mlr** there are *only* 165. 
However, the difference between both mainly breaks down to niche learners. 
The most used algorithms are available in both packages.
```

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +There are several resampling strategies available in both packages. Of course both include the most standard procedure (repeated) k-fold cross-validation. Moreover the strategies holdout, bootstrap a
> There are several resampling strategies available in both packages.

Maybe we can try to left out such statements as they repeatedly use the word "both" and "packages" and it should be well known that both usually come with more than 1 learner or 1 resamp strategy :)

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +In **mlr** there are currently [71 measures](https://mlr.mlr-org.com/articles/tutorial/measures.html) implemented for all the different tasks that can be handled in **mlr**. Custom measures can be ad
```suggestion
In **mlr** there are currently [71 measures](https://mlr.mlr-org.com/articles/tutorial/measures.html) implemented for all the different tasks that can be handled in **mlr**. 
Custom measures can be added by the user (see [here](https://mlr.mlr-org.com/articles/tutorial/create_measure.html)). 
Only one measure is given as default (Mean Squared Error (`mse`) for regression and the Mean Misclassification Error (`mmce`) for classification).
```

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +**caret** has two standard measures that are used for each of the tasks (RMSE and Rsquared for regression and Accuracy and Kappa for classification). They are changeable via the ```trainControl``` ar
```suggestion
**caret** has two standard measures that are used for each of the tasks (Root Mean Square Error (RMSE) and R² (Rsquared) for regression and Accuracy and Kappa for classification). 
They are changeable via the `trainControl` argument but it is more complicated than with **mlr**.
```

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +**mlr** provides the function ```benchmark``` for executing a comparison of several learners and several datasets/tasks at once (also parallelizable). No such functionality is available in **caret**.
```suggestion
**mlr** provides the function ```benchmark``` for executing a comparison of several learners and several datasets/tasks at once (even in parallel). No such functionality is available in **caret**.
```

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +In **mlr** tuning is not done automatically. There are functions and wrappers to perform the tuning. Tuning methods that are supported are random search, grid search, F-Racing and model-based optimiz
```suggestion
In **mlr** tuning is not done automatically. 
There are functions and wrappers to perform the tuning. 
Supported tuning methods are _random search_, _grid search_, _F-Racing_ and _model-based optimization_ via the **mlrMBO** package. 
Here is a code example with a simple tuning of a support vector machine:
```

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +The tuning strategy is defined in ```control```. For tuning while resampling a learner has to be wrapped via ```makeTuneWrapper```.
```suggestion
The tuning strategy is defined in `control`. 
For a nested tuning design a learner has to be wrapped via `makeTuneWrapper()`.
```

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +Tuning is done internally and automatically in the **caret** package. What is tuned is described in the [learner section](http://topepo.github.io/caret/train-models-by-tag.html) of the tutorial. This
```suggestion
Tuning is done internally and automatically in the **caret** package. 
What the tuning does is described in the [learner section](http://topepo.github.io/caret/train-models-by-tag.html) of the tutorial. 
This can be changed by the user to _grid search_ or _random search_ in `trainControl()`:
```

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +For both packages there are plots to visualize the tuning process, for example to plot the tuning parameters (1 or 2) vs. the performance or for plotting the development of the performance in the tun
> tuning parameters (1 or 2)

This is confusing. Need a bit more explanation.

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +Visualising your results and getting informations about your models is an important task in the modelling pipeline. Both packages provide a lot of possibilities here. For both packages we have ROC-An
```suggestion
Visualizing your results and getting information about the models is an important task in the modeling pipeline. 
For both packages we have ROC-Analysis and calibration curves. 
**mlr** provides additionally partial dependence plots, learning curves, cut-off curves and residual plotting, while **caret** comes with specific variable importance methods and lift curves.
```

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +**mlr** provides 16 already build tasks. Moreover in **mlr** there is a nice connection to the [**OpenML**](https://github.com/openml/openml-r) package and its [online platform](https://www.openml.or
```suggestion
**mlr** provides 16 already built tasks. Moreover in **mlr** there is a nice connection to the [**OpenML**](https://github.com/openml/openml-r) package and its [online platform](https://www.openml.org/) with over 20000 datasets from all domains.
```

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +There shouldn`t be a big time difference for the operations of the package itself as most of the operations are not computationally intensive.
This is an important point here. We should definitely add more content here.

Maybe a small profvis() comparison for a small task?

And state that most costly operations depend on the respective learner packages used?

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +**caret** has prespecified tuning if the learners are used in their default version so it will take more time than **mlr** for which tuning is not done in the default method. In the first example abo
> **caret** has prespecified tuning if the learners are used in their default version so it will take more time than **mlr** for which tuning is not done in the default method

This can be confusing. You are refering to a normal `train()` call here but it can also sound like a speed comparison stating that caret is slower than mlr. 

We should be more specific here.

> In general the automatic tuning of **caret** will also lead to better performance.

This statement is not really fair since mlr does not tune by default at all? And if, it is probably better?

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +In contrast in **mlr** you have more options. You can parallelize on different [levels](https://mlr.mlr-org.com/articles/tutorial/parallelization.html): While using benchmark with different learners
```suggestion
In contrast in **mlr** offers more options. 
Parallelization can be done on different [levels](https://mlr.mlr-org.com/articles/tutorial/parallelization.html): 
- when benchmarking different learners and datasets, 
- when resampling
- when selecting features
- while tuning hyperparameters and 
- while training an ensemble. 

Parallelization is done via [**parallelMap**](https://cran.r-project.org/web/packages/parallelMap/index.html) which works with all major parallelization backends: [**parallel**](https://stat.ethz.ch/R-manual/R-devel/library/parallel/doc/parallel.pdf), [**snow**](https://cran.r-project.org/web/packages/snow/index.html) or [**batchtools**](https://cran.r-project.org/web/packages/batchtools/batchtools.pdf). Especially useful is the function ```batchmark``` which is good for parallelizing benchmarks via [**batchtools**](https://cran.r-project.org/web/packages/batchtools/batchtools.pdf).
```

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +In **mlr** you have an object for every part of the process: a task, a learner, a measure, a resample object. In **caret** you have the ```trainControl``` object that is used in ```train``` which is
```suggestion
In **mlr** you have an object for every part of the process: a task, a learner, a measure, a resample object. 
In **caret** you have the ```trainControl``` object that is used in `train()`, but it feels that **mlr** is more intuitive and clear here.
```

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +**mlr** developers are currently working on [**mlr3**](https://github.com/mlr-org/mlr3) which aims at being even more extensible and using **R6**, **data.table** and other useful packages that were n
```suggestion
**mlr** developers are currently working on [**mlr3**](https://github.com/mlr-org/mlr3) which aims at being even more extensible and uses **R6**, **data.table**, **future** and other useful packages that were not used when **mlr** was released back in the years.
```

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +<!--## Overview in table -->
Would be cool, yes.

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +Thanks to Rahul Sangole, who helped me a bit with informations about the **caret** package as I was not very familiar with it. This blog post also appears on my [personal blog site](http://philipppro
```suggestion
Thanks to [Rahul Sangole (@rsangole)](https://github.com/rsangole), who helped with information about the **caret** package.
This blog post also appears on the [personal blog site](http://philipppro.github.io/) of @PhilippPro.
```

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +authors: ["philipp-probst"]
```suggestion
authors: ["philipp-probst", "patrick-schratz"]
```

2018-12-06 10:25 UTC, pat-s commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +authors: ["philipp-probst"]
Also add @rsangole 	here (after a blog author entry was added to the website).

2018-12-11 16:41 UTC, PhilippPro reviewed
Some comments on the comments. ;) I think some of the open points require quite a big amount of time, that I currently do not have.

2018-12-11 16:41 UTC, PhilippPro commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +> *The caret package (short for Classification And REgression Training) is a set of functions that attempt to streamline the process for creating predictive models.*
this is already correct.

2018-12-11 16:41 UTC, PhilippPro commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +**caret** provides more things. There is the [Applied Predictive Modelling book](https://www.springer.com/de/book/9781461468486) which tries to *cover the overall predictive modeling process.* It is
Hmm, I think it is not so bad to list some books for the R-Blogger readers, especially when they are freely available.

2018-12-11 16:41 UTC, PhilippPro commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +Moreover there is a [datacamp course](https://www.datacamp.com/courses/machine-learning-toolbox) that uses **caret**.
The problem is, that as far as I know there is no non-commercial platform that offers things like that, otherwise I would link it...

2018-12-11 16:41 UTC, PhilippPro commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +```{r, eval = FALSE}
We can set it to TRUE.

2018-12-11 16:41 UTC, PhilippPro commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +In this code you can already see a crucial difference. In **mlr** you have to create a task and a learner. This means more code writing, but gives the user also more flexibility and overview of what
This is like opening a big box.... ;)

2018-12-11 16:41 UTC, PhilippPro commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +There are several resampling strategies available in both packages. Of course both include the most standard procedure (repeated) k-fold cross-validation. Moreover the strategies holdout, bootstrap a
How would you write it?

2018-12-11 16:41 UTC, PhilippPro commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +**caret** has prespecified tuning if the learners are used in their default version so it will take more time than **mlr** for which tuning is not done in the default method. In the first example abo
I just state what the packages do in their default mode.

2018-12-11 16:41 UTC, PhilippPro commented on content/docs/2018-11-20-mlr-vs-caret.Rmd
> +**mlr** developers are currently working on [**mlr3**](https://github.com/mlr-org/mlr3) which aims at being even more extensible and using **R6**, **data.table** and other useful packages that were n
data.table was already available.

2020-11-13 05:58 UTC, pat-s commented
I think we missed the point for publishing this.

2020-11-13 05:58 UTC, closed without merging

2020-11-13 17:54 UTC, PhilippPro commented
It is ok, I just published it on my blog site and it is getting a lot of attention according to google statistics. :)

2020-11-13 17:56 UTC, PhilippPro commented
Some small critics from my side: I put some effort regarding this blog post but nobody replied in time. That was not really helpful and not really motivating to make a further contribution to the mlr blog.

2020-11-13 21:45 UTC, pat-s commented
Yeah totally understandable. We are lacking clear responsibilities in parts - this repo is one.